/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.chart.series.Pie'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    title: 'lsjlajsdlkasd',
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            title: '',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'String'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Number'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'Date'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Boolean'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    bodyPadding: 10,
                                    title: 'My Form',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'chart',
                                    flex: 1,
                                    height: 250,
                                    width: 400,
                                    animate: true,
                                    insetPadding: 20,
                                    series: [
                                        {
                                            type: 'pie',
                                            label: {
                                                field: 'x',
                                                display: 'rotate',
                                                contrast: true,
                                                font: '12px Arial'
                                            },
                                            showInLegend: true,
                                            angleField: 'y'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'treepanel',
                    region: 'west',
                    width: 150,
                    title: 'Menu',
                    viewConfig: {

                    }
                },
                {
                    xtype: 'container',
                    region: 'north',
                    height: 43,
                    html: 'Meu Projeto'
                }
            ]
        });

        me.callParent(arguments);
    }

});